"use client";

import type { GenerationResult } from "@/app/page";
import styles from "./PreviewPanel.module.css";

interface PreviewPanelProps {
  result: GenerationResult | null;
  isLoading: boolean;
}

export function PreviewPanel({ result, isLoading }: PreviewPanelProps) {
  if (isLoading) {
    return (
      <div className={styles.panel}>
        <div className={styles.loading}>
          <div className={styles.spinner} />
          <p>デザインを生成中...</p>
          <p className={styles.loadingHint}>
            選択したアートディレクターの哲学を適用しています
          </p>
        </div>
      </div>
    );
  }

  if (!result) {
    return (
      <div className={styles.panel}>
        <div className={styles.empty}>
          <div className={styles.emptyIcon}>🎨</div>
          <p>プロジェクト情報を入力し、</p>
          <p>アートディレクターを選択してください</p>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.panel}>
      <div className={styles.header}>
        <span className={styles.agentLabel}>
          Generated by <strong>{result.agentName}</strong>
        </span>
        <span
          className={`${styles.qaScore} ${result.qaScore >= 80 ? styles.good : result.qaScore >= 60 ? styles.warning : styles.bad}`}
        >
          QA Score: {result.qaScore}/100
        </span>
      </div>

      {result.qaIssues.length > 0 && (
        <div className={styles.issues}>
          <p className={styles.issuesTitle}>QA Issues:</p>
          <ul>
            {result.qaIssues.map((issue, i) => (
              <li key={i}>{issue}</li>
            ))}
          </ul>
        </div>
      )}

      <div className={styles.preview}>
        <iframe
          srcDoc={`<!DOCTYPE html>
<html>
<head>
  <style>${result.css}</style>
</head>
<body>
  ${result.html}
</body>
</html>`}
          title="Design Preview"
          className={styles.iframe}
        />
      </div>

      <div className={styles.actions}>
        <button className={styles.actionButton}>HTMLをコピー</button>
        <button className={styles.actionButton}>CSSをコピー</button>
        <button className={`${styles.actionButton} ${styles.primary}`}>
          ダウンロード
        </button>
      </div>
    </div>
  );
}
